### ISSUE TITLE
Loose Ammo

### ISSUE THREAD

**Issue by SDGNelson** [SmartlyDressedGames/Unturned-4.x-Community#104]
Take bullets out of a magazine even when you don't have a box to put them in.

- [x] Ammunition containers/individual data assets
- [x] Ammunition containers get # ammo from attached items
- [x] Item instance userwidget overlays from data asset
- [x] AmmunitionQuantity overlay
- [x] Convert attachment slots horizontal box into Details vertical box. Show attachment slot title with dropable socket, and additional information about current items.
- [x] Multiple output find by slot/by class
- [x] Attachment slots that support multiple items. "+" button to drop new attachments in
- [x] Horizontal details box for not bAllowMultipleAttachedItemInstances
- [x] Stackable InventoryItem interface and StackableAmmunition implementation
- [x] Stackable controller
- [x] Moveable window popup for split size prompt
- [x] Drag op helpers which handle quantity vs non quantity
- [x] Improve quantity menu
- [x] Attaching quantity
- [x] Splitting/merging in and out of stackable storage
- [x] Ammunition overlay for gun (IInventoryItemWithAmmunition Interface?)
- [x] Fix quantity option when dropping into large container to use max of split-able size and container size
- [x] Fix attaching item to itself
- [x] Move inventory UI helpers into separate function library
- [x] Non-observable attachments (don't show bullets model on mag)
- [x] 5.56mm bullets world model
- [x] Rename instance overlays to at-a-glance
- [x] Get ammunition overlay from base item data asset check implements interface
- [x] Overridable drop handler class
- [x] Move all drop handler code to c++ out of socket user widgets 
- [x] Drop ammo crate onto mag to fill
- [x] No filling mags that are attached to guns
- [x] Tidy up name and desc formatting

**Comment by SnowEdwin** [comment]
*escape from tarkov intensifies*
even though that's a joke that's not even a bad thing
