### ISSUE TITLE
Test Item for Each Wearable Slot

### ISSUE THREAD

**Issue by SDGNelson** [SmartlyDressedGames/Unturned-4.x-Community#130]
- [x] Shirt: Tee
- [x] Pants: Jeans
- [x] Gloves: Fingerless
- [x] Shoes: Sneakers
- [x] Belt: Leather Belt
- [x] Vest: Ballistic Vest
- [x] Backpack: MOLLE Rucksack
- [x] Sling: Quiver
- [x] Wrists: Watch
- [x] Neck: Dogtags
- [x] Glasses: Regular
- [x] Mask: Balaclava
- [x] Hat: Baseball Cap
- [x] Overcoat: Hoodie
- [x] Rucksack buckles and pins
- [x] Military camo textiles
- [x] Covered/uncovered versions of Hoodie
- [x] Covered/uncovered versions of Tee
- [x] Hoodie zipper

**Comment by SnowEdwin** [comment]
>hoodie zipper
a block in time
