### ISSUE TITLE
Spawnable item setup class

### ISSUE THREAD

**Issue by SDGNelson** [SmartlyDressedGames/Unturned-4.x-Community#220]
Enables multiple configurations for how an item can spawn
- [x] Candidate for item spawn tables
- [x] Subclass for textile setup
- [x] Base item + attached items
- [x] Holographic setup
- [x] Remove old spawnable modifier classes
- [x] Pickup accepts UInventoryItemTemplate
- [x] Amount of ammo in container

**Comment by NarcoletpicHound** [comment]
Don't do testing without me my guy!
