### ISSUE TITLE
My project may die.

### ISSUE THREAD

**Issue by VitaxaRusModding** [SmartlyDressedGames/Unturned-4.x-Community#259]
I have a big servers project for Unturned 3.0
I know c #
I work well in a unity engine.
The problem is that I don't know what will happen after release 4.0.
I am afraid that my project will be threatened with dying, because I do not know c ++ and have never worked with an unreal engine.
And I understand that these are my problems, I would like to hear your opinion.

**Comment by Adamv21** [comment]
Well, not too much to do about it I think. My experience with C++ isn't the best but it was indeed working, if you know what I mean. If you know the fundamentals of C# with some work you can transform to C++ withut a doubt, what's the project about though?

**Comment by VitaxaRusModding** [comment]
Project unique servers

**Comment by SDGNelson** [comment]
Your knowledge will carry over nicely between game engines and languages, but that said 3 is going to be around for a long time - you can still continue development of your project. Using blueprint in 4 will also be a good option for you.
