### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by DiFFoZ** [SmartlyDressedGames/Unturned-4.x-Community#272]
![image](https://user-images.githubusercontent.com/48765566/62417097-bc67f500-b671-11e9-8dfd-787121b6a851.png)

**Comment by DiFFoZ** [comment]
![image](https://user-images.githubusercontent.com/48765566/62417194-fc2fdc00-b673-11e9-9d27-306f578ea2ac.png)
As I understand it, I took 2 Eaglefire right away (one on hand)

**Comment by MoltonMontro** [comment]
@SDGNelson I believe this issue (double guns) was resolved a couple patches ago now?
