### ISSUE TITLE
[Sug] Color system

### ISSUE THREAD

**Issue by TinyGiraffes** [SmartlyDressedGames/Unturned-4.x-Community#277]
Hello, I wanted to suggest that you build a different system for color varying objects. Things like backpacks or cars are tedious for modders to make and for admins to spawn. I'm a little too ignorant to know how a better system would work. I was thinking the system could be used in more ways like shipping containers or clothing qualities, as in modders could add blue shirts to the item shirt. A system where modders only had to add additional types instead of full objects and admins could spawn one object and perhaps open a menu, like Gmod hold c and right-click, to adjust which variant it is would be very helpful. This, of course, is not a necessity but I thought it was a worthwhile thought. Have a good life :D

**Comment by SDGNelson** [comment]
It is definitely tedious to do with the current systems. Making variants easier was one of the core goals for items in Unturned II. Material collections were added for objects in 3, but something for items and vehicles is less likely at this point.
