### ISSUE TITLE
Clothed Skeletal Mesh Cleanup

### ISSUE THREAD

**Issue by SDGNelson** [SmartlyDressedGames/Unturned-4.x-Community#39]
- [x] Fix up limb hiding
- [x] List of attached skeletal meshes
- [x] Consistent visibility
- [x] List of attached static meshes
- [x] Per-wearable bone extensions

**Comment by NarcoletpicHound** [comment]
Did you make the head smaller though?

**Comment by V1CeNtE** [comment]
small head = difficult to execute a headshot

**Comment by SnowEdwin** [comment]
i'm pretty sure that was the poin
