### ISSUE TITLE
Recoil

### ISSUE THREAD

**Issue by SDGNelson** [SmartlyDressedGames/Unturned-4.x-Community#47]
- [x] Bullet Index -> Recoil Offset
- [x] Random Recoil
- [x] Recoil Recovery
- [x] Spread
- [x] Spread Recovery
- [x] Scale crosshair by FoV -> UI size
- [x] Visual Recoil

**Comment by NarcoletpicHound** [comment]
Recoil coming in!  Nice job Nelson, but this time in 4.x can we have it not be so reliant on the Sharpshooter skill?

**Comment by SnowEdwin** [comment]
also do the rounds follow the center of the screen or the actual sight/barrel

please be the latter

please have proper collimators later on
