### ISSUE TITLE
Attachments

### ISSUE THREAD

**Issue by SDGNelson** [SmartlyDressedGames/Unturned-4.x-Community#57]
- [x] Gun attachments animation
- [x] Change attachments input key
- [x] Sight alignment
- [x] ADS
- [x] Fix pitch parenting
- [x] Red dot sight
- [x] Hide crosshair while aiming
- [x] Aiming recoil multipliers
- [x] Show slot locations
- [x] Cursor focus
- [x] Third person ADS animation
- [x] Container handles ownership change
- [x] Attachment state knows which slot it is

**Comment by SnowEdwin** [comment]
hoping for an aimpoint
