### ISSUE TITLE
Character Opinion

### ISSUE THREAD

**Issue by V1CeNtE** [SmartlyDressedGames/Unturned-4.x-Community#58]
I think the character is fine but, something I did not like and that was the **wide**
I think **it does not fit with him and he looks weird**

this is what I mean: http://prntscr.com/h93o6z

Does it make sense to what I say?

**Comment by SnowEdwin** [comment]
...you want him to be a bit THINNer?

honestly i want at least the arms to be thinner, they take up so much space on screen in first person as is (albeit so does 3.0 but it's an issue there too so)

**Comment by V1CeNtE** [comment]
it looks so weird with his body like that,idk,it  need remodel.probably Nelson would have to make a new model and see it fine as much as in photos as in gameplay

**Comment by SDGNelson** [comment]
It is thinner than 3.0, however wide enough to retain the Unturned character aesthetic. I'm quite pleased with it.
