### ISSUE TITLE
Throw Weapons/Items With Input Key In Any Instance

### ISSUE THREAD

**Issue by V1CeNtE** [SmartlyDressedGames/Unturned-4.x-Community#70]
This feature **would be useful** because you dont need to open your inventory and drop item.

**examples:** 
 **-if you want to throw a weapon to your friend in highs just press the key with the perfect power and done (it would be good auto equip weapons in instead)**

**-throw items perfeclty in holes or specific sites.**

**Comment by SnowEdwin** [comment]
so basically everything is a grenade
n i c e

**Comment by V1CeNtE** [comment]
but not throwing with high power

**Comment by SnowEdwin** [comment]
i could get that for heavy stuff, but light stuff? c'mon.
i wanna throw a can of beans so hard it smashes a dude's head in >:(

**Comment by SDGNelson** [comment]
Could be added at some point, but not a focus right now. Maybe on a low traffic key like U.

**Comment by V1CeNtE** [comment]
thanks for answering
