### ISSUE TITLE
Adjust Scope Zoom With Mouse Wheel

### ISSUE THREAD

**Issue by V1CeNtE** [SmartlyDressedGames/Unturned-4.x-Community#74]
**AIMING AND SCROLL UP THE WHEEL**
example:

zooming x1 to x16 or limiting depending on the range x8, x7, x20

**Comment by NarcoletpicHound** [comment]
Hell yeah, I approve of this

**Comment by SDGNelson** [comment]
Will probably be added at some point.

**Comment by V1CeNtE** [comment]
Thanks Nelson
