### ISSUE TITLE
Cleaning Day

### ISSUE THREAD

**Issue by SDGNelson** [SmartlyDressedGames/Unturned-4.x-Community#78]
- [x] Organize folder structure more especially UI stuff
- [x] Basic loading screen
- [x] Document code style in wiki
- [x] Move to projects folder
- [x] Automate doxygen upload
- [x] Go over older code and bring up to date
- [x] DenizenCharacter.h cleanup
- [x] Setup build server
- [x] Decide what to do about Unturned.h macros
- [x] Fix component/actor naming
- [x] Move all possible blueprint logic to C++
- [x] Fix event driven loader crash

**Comment by Savagethepanda** [comment]
Is it spring cleaning already.

**Comment by SnowEdwin** [comment]
nice day my dude
